---
name: 'Check links'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check links
        uses: lycheeverse/lychee-action@9ace499fe66cee282a29eaa628fdac2c72fa087f # v1.6.1
        with:
          args: "--exclude-all-private --exclude-mail --exclude-path ./layouts --include-verbatim --max-concurrency 32 --require-https --verbose --no-progress './**/*.md' './**/*.html'"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
