---
name: 'Check links'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check links
        uses: lycheeverse/lychee-action@01d72a032635cc56bf23e901b9d5fb3272419ca1 # v1.7.0
        with:
          args: "--exclude-all-private --exclude-mail --exclude-path ./layouts --include-verbatim --max-concurrency 32 --require-https --verbose --no-progress './**/*.md' './**/*.html'"
          fail: true
          lycheeVersion: 0.10.3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
